<?php

namespace AppBundle\Repository;

/**
 * LieuEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
