<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Billet;
use AppBundle\Entity\Evenement;
use AppBundle\Entity\TypeBillet;
use DateTime;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LockedSeatRepository extends EntityRepository
{
    /**
     * @param int $time temps de différence maximum pour supprimer les places
     *
     */
    public function getLockedSeatToRemove($time=600){
        $now_tstamp= time();
        return $this->getEntityManager()->createQuery('delete FROM AppBundle:LockedSeat as ls where :timestamp - ls.time > :time ')
                ->setParameter('time',$time)
                ->setParameter('timestamp',$now_tstamp)
                ->execute();
    }


}
