<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Evenement;
use AppBundle\Entity\LieuEvenement;
use AppBundle\Entity\TypeBillet;
use AppBundle\Entity\Reservation;
use Doctrine\ORM\EntityRepository;
/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    /** @fonction Générer une réservation aves des billets
     * @param Billet|null $listeBillet
     * @param Evenement $event
     */
    public function createReservation(Billet $listeBillet=null,Evenement $event )
    {

    }
}
