app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_registration_register:
    path: /inscription
    controller: AppBundle\Controller\RegistrationController::registerAction
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
