vich_uploader:
  db_driver: orm
  mappings:
    event_image:
      uri_prefix:         /img/events
      upload_destination: '%kernel.root_dir%/../web/img/events'
      namer:              vich_uploader.namer_uniqid
      inject_on_load: false
      delete_on_update:   true
      delete_on_remove:   true